### ISSUE TITLE
Some questions about the project

### ISSUE THREAD

**Issue by QuangMuop** [vit0r/springboot-oauth2-jwt-jpa#1]
Hi @vit0r , your project is very good starter for spring security using oauth2, but I meet some problems not yet understand. Could you help me yo explain,
1. from the result of _oauth/token_, it has field **jti**, what does it for?
2. how to gen new access_token from refresh_token?
3. when I test with postman for api _api/v1/home/get_ I met error "An Authentication object was not found in the SecurityContext", how to solve it?
Thank you so much!

**Comment by vit0r** [comment]
Hi @QuangMuop,

1. The jti (JWT ID) claim provides a unique identifier for the JWT. The identifier value MUST be assigned in a manner that ensures that there is a negligible probability that the same value will be accidentally assigned to a different data object. The jti claim can be used to prevent the JWT from being replayed. The jti value is a case-sensitive string. Use of this claim is OPTIONAL.
2. refresh_token not implemented yet
3. in header send Authorization: Bearer "youtoken"
